### ISSUE TITLE
"Adding A New Effect" Guide

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/reboundx#10]
## [Adding A New Effect](https://reboundx.readthedocs.io/en/latest/add_effect.html)
Thought we should create a separate issue for the following:
- Track any issues we come across in following the "Adding A New Effect" guide.
- Document any typos, questions, areas of improvement, and general feedback for Dr. Tamayo re: the guide.

**Comment by sabaronett** [comment]
### Stark Force
@Nofe4108 , I added a basic "Stark Force" effect following Secs. 6.1 - 6.2 to the `mass_loss` repo. See https://github.com/sabaronett/reboundx/commit/8537b18d6d7a1ce616db598adca0f7ef6bc733a2 for more details. After pulling the changes to your local, you may need to:
`cd your_path_to/reboundx/scripts`
`python add_new_effect.py`
before running `make clean` and `make` inside the `examples/stark_force` dir.

I suggest going through the changes/addition I made in following the guide, and make sure they work for yourself. I've also included sample graphs ("Figure_1" and "Figure_2") to see what a successful run with `sim_reader.py` should produce.

Let me know if you have any questions or run into any issues.

**Comment by sabaronett** [comment]
### Migration Force
@Nofe4108 , similar to the "Stark Force," this "Migration Force" is a _non-conservative_ example of a force that I'll be largely basing the `tidal_drag` effect from. See https://github.com/sabaronett/reboundx/commit/2c8f9f0ca7d7258073daaae109c6ebe70fe8f68a for details.

**Comment by sabaronett** [comment]
[Typo](https://rebound.readthedocs.io/en/latest/c_api_mainrebstructs.html#_CPPv4N14MainRebStructsUt6_anon_3E): Says "Available collision routines." Should say "Available visualization options."

Corrected in https://github.com/hannorein/rebound/pull/407

**Comment by sabaronett** [comment]
Wrong target URL in last paragraph of https://reboundx.readthedocs.io/en/latest/add_effect.html#c-example:
> (See Sec. 2.4 of [OpenGL Keyboard Commands](http://rebound.readthedocs.org/en/latest/c_quickstart.html) for a list of the visualization keyboard commands)

_4/13/2020 Update_: Corrected in 542f3a490cb25eee8c98561121cbf790db7a6ea0

**Comment by sabaronett** [comment]
Created issue on main repo for documentation corrections: https://github.com/dtamayo/reboundx/issues/46.

Closing issue.

**Comment by sabaronett** [comment]
@dtamayo,

From: https://github.com/sabaronett/reboundx/blob/spline/doc/add_effect.rst#python-example
> We just need to make sure that whenever we change C code (like we did above), we reinstall REBOUNDx, i.e. pip install -e . in the root reboundx directory.

But ran into the following:
```bash
(rebx) stanley@PAVILION-13:~/github/sabaronett/reboundx$ ls
Dockerfile   README.rst  examples           scripts            version.txt
LICENSE      build       ipython_examples   setup.py
MANIFEST.in  dist        reboundx           src
Makefile     doc         reboundx.egg-info  update_version.py
(rebx) stanley@PAVILION-13:~/github/sabaronett/reboundx$ pip install -e

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument
```

I don't remember having an issue before. Is there something I'm doing wrong here?

**Comment by dtamayo** [comment]
Thanks for all of these Stanley, super helpful. I'll add these in when we merge the new stuff.

It should 'pip install -e .' the dot for current dir, not the end of sentence!  I'll make it less ambiguous, thanks!

**Comment by sabaronett** [comment]
Ah, I see it now... I should have just copied and pasted like I probably did before. Sorry about that.

**Comment by dtamayo** [comment]
No problem at all...it's ambiguous and others will do the same. I'll def fix it

**Comment by sabaronett** [comment]
All standing issues resolved.

Closing.
