### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/reboundx#2]
To recap you:
- Added simple mass-loss effect to `core.c` and `core.h`
- `core.o` doesn't recognize added operator

Have you tried the `make clean` command yet? (see [here](https://rebound.readthedocs.io/en/latest/c_quickstart.html#compiling-and-directory-structure)). It basically "un"-compiles all of REBOUND, allowing you to compile from the ground up (like the first time) with a simple `make` afterwards. Try that and let me know if that does the trick.

**Comment by Nofe4108** [comment]
Looks like that worked. Thanks! Now I just need to focus on getting the effect to actually do what I want it to do.
