### ISSUE TITLE
Create new "mesa2txt" repo

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/reboundx#24]
From https://github.com/sabaronett/reboundx/issues/22#issuecomment-606773524,
> I think the most logical way to organize it is if your example notebook just loads your txt files (taking them as given), and you create a separate repo that you can link to in your paper that shows people how to read a mesa output file and write out a text file. If we added the mesa reader into REBOUNDx and the example then for example if the mesa output format changes, then we have to update the REBOUNDx code. I think the cleanest is if we provide the minimal interface required in REBOUNDx (I.e. simple lists that you can load from text files or however you want) and leave all the rest to the user.

**Comment by dtamayo** [comment]
Or just mesa2txt! It doesn't have to be a complicated code...just a jupyter notebook showing how to write from mesa output to txt is all that's needed I think. In particular, I don't think a C implementation adds much in the end.

**Comment by sabaronett** [comment]
@dtamayo,

I created https://github.com/sabaronett/mesa2txt. Let me know what you think.

**Comment by sabaronett** [comment]
Dan added link to repo in ParameterInterpolation.ipynb, https://github.com/dtamayo/reboundx/pull/47#issuecomment-613492266.

Closing.
